# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jae-kang <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/08 17:19:31 by jae-kang          #+#    #+#              #
#    Updated: 2023/09/11 23:18:46 by jae-kang         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

TARGET = ft_cat
SRC = *.c

all : $(TARGET)

$(TARGET) : $(SRC)
	cc -o $(TARGET) $(SRC) -Iincludes

clean :

fclean :
	rm -rf $(TARGET)

re : fclean all
